### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp1-graph-pittore#1]
# ⚠️Travail baclé ⚠️ 
*La prochaine fois c'est 0, et sans remédiation*

- [x] le rapport

- [x] Ici le type pourrait être IGraph, pourquoi ?

https://github.com/PolytechLyon/isi3-tp1-graph-pittore/blob/33759ade89240c08d50ff11e014352cdfd210803/src/main/java/graph/UndirectedGraph.java#L8

- [ ] Node ne surcharge pas `hashcode`, quel est la conséquence ?

- [x] Tu ne profites pas tu toString de Node et d'Arc, c'est dommage
https://github.com/PolytechLyon/isi3-tp1-graph-pittore/blob/33759ade89240c08d50ff11e014352cdfd210803/src/main/java/graph/Graph.java#L71-L95

**Comment by axbator28** [comment]
Bonjour, 

* J'ai envoyé le rapport hier soir (je ne sais pas si je dois être plus précis au niveaux des interfaces dans les schémas UML, je n'y précise pas les fonctions/ attributs). Désolé pour le retard.

* J'ai changé le type de Graph à IGraph, ce qui n'est pas gênant car le classe Graph implémente IGraph, et cela permet d'être plus générique ( si on créait une nouvelle sorte de graphe implémentant IGraph, on pourrait aussi s'en servir pour l'adapter).

```java
public class UndirectedGraph implements IUndirectedGraph {
    private IGraph graphe;
```
Par contre, celà m'a rajouté des fonctions à implémenter (ce qui n'est pas gênant). Je pense particulièrement à addArc

* hashCode est la fonction qui va fournir un hash  (un integer propre à l'objet concerné) pour le Node.
Cette fonction est appelée par divers objets, comme les HashMap et HashSet que j'utilise.  Je ne suis pas sûr de moi, mais je dirais que, cela pourrait empêcher le bon fonctionnement de ces objets, avec, par exemple, l'insertion possible 2 fois de deux Node pourtant égaux. Il faut l'implémenter en récupérant le UniqueId? ?

* Et normalement, j'ai rajouter la méthode toString pour les arcs, car elle n'était pas utilisée pour le moment.

```java
	public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Graph \n");
		Set<Node> allNodes = getAllNodes();
        for(Node currentNode:allNodes) {
            List<Arc> arcs_current = adjacence.get(currentNode);
            builder.append("[Noeud=")
                    .append(currentNode.toString())
                    .append(" : ");
            if (arcs_current.isEmpty()) {
                builder.append("[]\n");
            }else{
            builder.append("[");
				for(Arc arc : arcs_current) {
					String arcsToString = new String();
					arcsToString = arc.toString();
					if (arcs_current.indexOf(arc) != arcs_current.size() - 1) {
						arcsToString += ", ";
					} else {
						arcsToString += "] \n";
					}
					builder.append(arcsToString);
				}
            }
        }
		return builder.toString();
	}
```

**Comment by Slashgear** [comment]
ça me va et oui il faudrait surcharger hascode avec UniqueID
